alias euler="python main.py"
alias activate_env="source env/bin/activate"
alias save_requirements="pip freeze > requirements.txt"
alias install_requirements="pip install -r requirements.txt"
alias python="python3"
alias pip="pip3"
alias download_results="gcloud compute scp --recurse philipp@phil:~/euler/results ./results"