alias euler="python main.py"
alias activate_env_windows="source env/Script/activate"
alias activate_env="source env/bin/activate"
alias create_env="python -m venv env"
alias save_requirements="pip freeze > requirements.txt"
alias install_requirements="pip install -r requirements.txt"
alias download_results="gcloud compute scp --recurse philipp@phil:~/euler/results ./results"